# BUILD PROJECT ##
FROM node:14.15.1-alpine as build
ARG environment

WORKDIR /workspace/
ADD package.json /workspace/
RUN npm install

COPY . /workspace/
RUN $(npm bin)/ng build --configuration=$environment

# FOR RUNNING TESTS ##
# (copy dist build-files)
# copy working files and install dependecies and chrome for test run
FROM nginx:1.19.5-alpine AS runtime

RUN apk update
RUN apk add --update nodejs npm


# Installs latest Chromium package
RUN apk update && apk add --no-cache chromium \
    chromium-chromedriver
ENV CHROME_BIN /usr/bin/chromium-browser


COPY  --from=build /workspace/dist/ /usr/share/nginx/html/
COPY --from=build /workspace/ /spring-petclinic-angular/


EXPOSE 8080

